<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:44</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Daycare6hrs'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:44</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Petsitter24'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:44</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LD:Interactions_Solo_GoToRabbitHole_PlasticSurgery_+20SP  "Super Interaction"'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LD:NPCDrama_SimGivingBirth_AtHospital "Away Super Interaction"'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Acquaintances'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_Roll'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Petsitter12'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_Heel'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole60'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Crush'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_ArtExhibition'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Friends_Family'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Hiking'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LD:Interactions_Solo_SocialHelper_GoToRabbitHole_FightAgainstBullying "Super Interaction"'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_VisitGynecologist_Abortion_Continue'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Date'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Church'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole_NPC30'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_Speak'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:45</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_sit'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LD:Interactions_Solo_GoToRabbitHole_SocialDramaClass  "Super Interaction"'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_TechMuseum'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Daycare4hrs'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole120'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LD:Interactions_Solo_SocialHelper_GoToRabbitHole_FightAgainstDomesticAbuse "Super Interaction"'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Petsitter'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Daycare8hrs'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_Fetch'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.roommateNPC_Rabbithole_Absent'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Petsitter8'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Circus'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_lieDown'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainerOwner_Continue'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_PlayDead'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:46</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Daycare2hrs'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:47</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LD:NPCDrama_SimGivingBirth_AtHospital_NPC "Away Super Interaction"'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:47</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_CookingContest'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:47</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_Shake'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:47</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_VisitGynecologist_SigOther'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:47</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.roommateNPC_Rabbithole_GoEat'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:47</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_ReadMeet'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:47</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_VisitGynecologist'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:47</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Friends'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:47</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LD:Interactions_Solo_SocialHelper_GoToRabbitHole_FightAgainstAnimalAbuse "Super Interaction"'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:47</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole_NPC60'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:48</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LD:Interactions_Solo_SocialHelper_GoToRabbitHole_SupportTheLGBTQA+Community "Super Interaction"'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:48</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_MiniVacation'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:48</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Honeymoon'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:48</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.roommateNPC_Rabbithole'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:48</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Daycare10hrs'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:48</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole30'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:48</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LD:Interactions_Solo_GoToRabbitHole_PlasticSurgery_+20SP_Continuation  "Super Interaction"'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:48</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_RockConcert'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:48</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole_NPC120'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>8c861afd92cfbff7605bc40e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2021-03-24 16:03:48</createtime><buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release</buildsignature><categoryid>interaction.py:1965</categoryid><desyncid>8c861afd92cfbff7605bc40e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] Exception in &lt;class 'sims4.tuning.instances.LD:Interactions_Solo_SocialHelper_GoToRabbitHole_FightAgainstRacism "Super Interaction"'&gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&#13;&#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&#13;&#10;Client Session Time: 247.55&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,95,47231&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&#13; &#10;</desyncdata></report>
</root>